// <auto-generated/>
global using global::System;
global using global::System.Collections.Generic;
global using ControleDeBar.ConsoleApp.Compartilhado;
global using ControleDeBar.ConsoleApp.ModuloGarcom;
global using ControleDeBar.ConsoleApp.ModuloMesa;
global using ControleDeBar.ConsoleApp.ModuloProduto;
global using ControleDeBar.ConsoleApp.ModuloConta;
global using ControleDeBar.ConsoleApp.ModuloPrincipal;

